version: "2.3"

services:
  postgres:
    container_name: pastebin-userver-database
    image: postgres:15
    environment:
      - POSTGRES_DB=pastebin
      - POSTGRES_USER=pastebin
      - POSTGRES_PASSWORD=pastebin
    ports:
      - 5432
    volumes:
      - ./postgresql/schemas:/docker-entrypoint-initdb.d
      - ./.pgdata:/var/lib/postgresql/data
    networks:
      - postgres

  userver_sample-container:
    image: ghcr.io/userver-framework/ubuntu-userver-build-base:v1
    container_name: pastebin-userver-server
    privileged: true
    environment:
      - POSTGRES_DB=pastebin
      - POSTGRES_USER=pastebin
      - POSTGRES_PASSWORD=pastebin
      - PREFIX=${PREFIX:-~/.local}
      - CC
      - CCACHE_DIR=/userver_sample/.ccache
      - CCACHE_HASHDIR
      - CCACHE_NOHASHDIR
      - CCACHE_PREFIX
      - CCACHE_SIZE
      - CMAKE_OPTS
      - CORES_DIR=/cores
      - CXX
      - MAKE_OPTS
      - CMAKE_OPTIONS
    volumes:
      - .:/userver_sample:rw
      - ./third_party/userver/tools/docker:/tools:ro
      - ${TC_CORES_DIR:-./.cores}:/cores:rw
    ports:
      - 8080:8080
    working_dir: /userver_sample
    entrypoint:
      - /tools/run_as_user.sh
    depends_on:
      - postgres
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
